INDICATOR_TYPES = {
    # Overall rankings and scores
    "Ease of Doing Business rank": int,
    "Ease of doing business score (DB17-20 methodology)": float,
    "Ease of doing business score (DB15 methodology)": float,
    "Ease of doing business score (DB10-14 methodology)": float,
    
    # Starting a business
    "Rank-Starting a business": int,
    "Score-Starting a business": float,
    "Procedures - Men (number)": float,
    "Score-Procedures - Men (number)": float,
    "Time - Men (days)": float,
    "Score-Time - Men (days)": float,
    "Cost - Men (% of income per capita)": float,
    "Score-Cost - Men (% of income per capita)": float,
    "Procedures - Women (number)": int,
    "Score-Procedures - Women (number)": float,
    "Time - Women (days)": int,
    "Score-Time - Women (days)": float,
    "Cost - Women (% of income per capita)": float,
    "Score-Cost - Women (% of income per capita)": float,
    "Paid-in Minimum capital (% of income per capita)": float,
    "Score-Paid-in Minimum capital (% of income per capita)": float,
    
    # Construction permits
    "Rank-Dealing with construction permits": int,
    "Score-Dealing with construction permits (DB16-20 methodology)": float,
    "Score-Dealing with construction permits (DB06-15 methodology)": float,
    "Procedures (number)": int,
    "Score-Procedures (number)": float,
    "Time (days)": int,
    "Score-Time (days)": float,
    "Cost (% of Warehouse value)": float,
    "Score-Cost (% of Warehouse value)": float,
    "Building quality control index (0-15) (DB16-20 methodology)": int,
    "Score-Building quality control index (0-15) (DB16-20 methodology)": float,
    "Quality of building regulations index (0-2) (DB16-20 methodology)": int,
    "Quality control before construction index (0-1) (DB16-20 methodology)": int,
    "Quality control during construction index (0-3) (DB16-20 methodology)": int,
    "Quality control after construction index (0-3) (DB16-20 methodology)": int,
    "Liability and insurance regimes index (0-2) (DB16-20 methodology)": int,
    "Professional certifications index (0-4) (DB16-20 methodology)": int,
    
    # Getting electricity
    "Rank-Getting electricity": int,
    "Score-Getting electricity (DB16-20 methodology)": float,
    "Score-Getting electricity (DB10-15 methodology)": float,
    "System average interruption duration index (SAIDI) (DB16-20 methodology)": float,
    "System average interruption frequency index (SAIFI) (DB16-20 methodology)": float,
    "Minimum outage time (in minutes) (DB16-20 methodology)": int,
    "Price of electricity (US cents per kWh) (DB16-20 methodology)": float,
    "Reliability of supply and transparency of tariff index (0-8) (DB16-20 methodology)": int,
    "Score-Reliability of supply and transparency of tariff index (0-8) (DB16-20 methodology)": float,
    "Cost (% of income per capita)": float,
    "Score-Cost (% of income per capita)": float,
    "Total duration and frequency of outages per customer a year (0-3) (DB16-20 methodology)": int,
    "Mechanisms for monitoring outages (0-1) (DB16-20 methodology)": int,
    "Mechanisms for restoring service (0-1) (DB16-20 methodology)": int,
    'Regulatory monitoring (0-1) (DB16-20 methodology)': int,
    'Financial deterrents aimed at limiting outages (0-1) (DB16-20 methodology)': int,
    'Communication of tariffs and tariff changes (0-1) (DB16-20 methodology)': int,
    'Minimum outage time (in minutes)  (DB16-20 methodology)': int,
    
    # Property registration
    "Rank-Registering property": int,
    "Score-Registering property (DB17-20 methodology)": float,
    "Score-Registering property (DB05-15 methodology)": float,
    "Quality of land administration index (0-30) (DB17-20 methodology)": int,
    "Score-Quality of land administration index (0-30) (DB17-20 methodology)": float,
    "Reliability of infrastructure index (0-8) (DB17-20 methodology)": int,
    "Transparency of information index (0-6) (DB17-20 methodology)": int,
    "Geographic coverage index (0-8) (DB17-20 methodology)": int,
    "Land dispute resolution index (0-8) (DB17-20 methodology)": int,
    "Equal access to property rights index (-2-0) (DB17-20 methodology)": int,
    'Cost (% of property value)': float,
    'Score-Cost (% of property value)': float,

    
    # Credit
    "Rank-Getting credit": int,
    "Score-Getting credit (DB15-20 methodology)": float,
    "Score-Getting credit (DB05-14 methodology)": float,
    "Strength of legal rights index (0-10) (DB05-14 methodology)": int,
    "Score-Strength of legal rights index (0-10) (DB05-14 methodology)": float,
    "Depth of credit information index (0-6) (DB05-14 methodology)": int,
    "Score-Depth of credit information index (0-6) (DB05-14 methodology)": float,
    "Getting Credit total score (DB05-14 methodology)": float,
    "Strength of legal rights index (0-12) (DB15-20 methodology)": int,
    "Score-Strength of legal rights index (0-12) (DB15-20 methodology)": float,
    "Depth of credit information index (0-8) (DB15-20 methodology)": int,
    "Score-Depth of credit information index (0-8) (DB15-20 methodology)": float,
    "Getting Credit total score (DB15-20 methodology)": float,
    "Credit registry coverage (% of adults)": float,
    "Credit bureau coverage (% of adults)": float,
    
    # Minority investor protection
    "Rank-Protecting minority investors": int,
    "Score-Protecting minority investors (DB15-20 methodology)": float,
    "Score-Protecting minority investors (DB06-14 methodology)": float,
    "Extent of disclosure index (0-10)": int,
    "Score-Extent of disclosure index (0-10)": float,
    "Extent of director liability index (0-10)": int,
    "Score-Extent of director liability index (0-10)": float,
    "Ease of shareholder suits index (0-10) (DB06-14 methodology)": int,
    "Score-Ease of shareholder suits index (0-10) (DB06-14 methodology)": float,
    "Strength of investor protection index (0-30) (DB06-14 methodology)": float,
    "Ease of shareholder suits index (0-10) (DB15-20 methodology)": int,
    "Score-Ease of shareholder suits index (0-10) (DB15-20 methodology)": float,
    "Extent of shareholder rights index (0-6) (DB15-20 methodology)": int,
    "Score-Extent of shareholder rights index (0-6) (DB15-20 methodology)": float,
    "Extent of ownership and control index (0-7) (DB15-20 methodology)": int,
    "Score-Extent of ownership and control index (0-7) (DB15-20 methodology)": float,
    "Extent of corporate transparency index (0-7) (DB15-20 methodology)": int,
    "Score-Extent of corporate transparency index (0-7) (DB15-20 methodology)": float,
    "Strength of minority investor protection index (0-50) (DB15-20 methodology)": int,

    # Taxes
    "Rank-Paying taxes": int,
    "Score-Paying taxes (DB17-20 methodology)": float,
    "Score-Paying taxes (DB06-16 methodology)": float,
    "Payments (number per year)": int,
    "Score-Payments (number per year)": float,
    "Time (hours per year)": int,
    "Score-Time (hours per year)": float,
    "Total tax and contribution rate (% of profit)": float,
    "Score-Total tax and contribution rate (% of profit)": float,
    "Profit tax (% of profit)": float,
    "Labor tax and contributions (% of profit)": float,
    "Other taxes (% of profit)": float,
    "Time to comply with VAT refund (hours) (DB17-20 methodology)": float,
    "Score-Time to comply with VAT refund (hours) (DB17-20 methodology)": float,
    "Time to obtain VAT refund (weeks) (DB17-20 methodology)": float,
    "Score-Time to obtain VAT refund (weeks) (DB17-20 methodology)": float,
    "Score-Postfiling index (0-100) (DB17-20 methodology)": float,
    'Time to comply with a corporate income tax correction (hours) (DB17-20 methodology)': float,
    'Score-Time to comply with a corporate income tax correction (hours) (DB17-20 methodology)': float,
    'Time to complete a corporate income tax correction (weeks) (DB17-20 methodology)': float,
    'Score-Time to complete a corporate income tax correction (weeks) (DB17-20 methodology)': float,

    # Trading across borders
    "Rank-Trading across borders": int,
    "Score-Trading across borders (DB16-20 methodology)": float,
    "Score-Trading across borders (DB06-15 methodology)": float,
    "Time to export: Documentary compliance (hours) (DB16-20 methodology)": float,
    "Score-Time to export: Documentary compliance (hours) (DB16-20 methodology)": float,
    "Cost to export: Documentary compliance (USD) (DB16-20 methodology)": float,
    "Score-Cost to export: Documentary compliance (USD) (DB16-20 methodology)": float,
    "Time to import: Documentary compliance (hours) (DB16-20 methodology)": float,
    "Score-Time to import: Documentary compliance (hours) (DB16-20 methodology)": float,
    "Cost to import: Documentary compliance (USD) (DB16-20 methodology)": float,
    "Score-Cost to import: Documentary compliance (USD) (DB16-20 methodology)": float,
    "Documents to export (number) (DB06-15 methodology)": int,
    "Score-Documents to export (number) (DB06-15 methodology)": float,
    "Documents to import (number) (DB06-15 methodology)": int,
    "Score-Documents to import (number) (DB06-15 methodology)": float,
    'Time to export: Border compliance (hours) (DB16-20 methodology)': float,
    'Score-Time to export: Border compliance (hours) (DB16-20 methodology)': float,
    'Time to import: Border compliance (hours) (DB16-20 methodology)': float,
    'Score-Time to import: Border compliance (hours) (DB16-20 methodology)': float,
    'Cost to export: Border compliance (USD) (DB16-20 methodology)': float,
    'Score-Cost to export: Border compliance (USD) (DB16-20 methodology)': float,
    'Cost to import: Border compliance (USD) (DB16-20 methodology)': float,
    'Score-Cost to import: Border compliance (USD) (DB16-20 methodology)': float,
    'Cost to export (US$ per container deflated) (DB06-15 methodology)': float,
    'Score-Cost to export (US$ per container deflated) (DB06-15 methodology)': float,
    'Cost to import (US$ per container deflated) (DB06-15 methodology)': float,
    'Score-Cost to import (US$ per container deflated) (DB06-15 methodology)': float,
    'Time to export (days) (DB06-15 methodology)': float,
    'Score-Time to export (days) (DB06-15 methodology)': float,
    'Time to import (days) (DB06-15 methodology)': float,
    'Score-Time to import (days) (DB06-15 methodology)': float,
    'Procedures (number) (DB04-15 methodology)': int,
    'Score-Procedures (number) (DB04-15 methodology)': float,

    # Contract enforcement
    "Rank-Enforcing contracts": int,
    "Score-Enforcing contracts (DB17-20 methodology)": float,
    "Score-Enforcing contracts (DB04-15 methodology)": float,
    "Filing and service (days)": int,
    "Trial and judgment (days)": int,
    "Enforcement of judgment (days)": int,
    "Cost (% of claim)": float,
    "Score-Cost (% of claim)": float,
    "Attorney fees (% of claim)": float,
    "Court fees (% of claim)": float,
    "Enforcement fees (% of claim)": float,
    "Quality of judicial processes index (0-18) (DB17-20 methodology)": int,
    "Score-Quality of judicial processes index (0-18) (DB17-20 methodology)": float,
    "Court structure and proceedings (0-5) (DB17-20 methodology)": int,
    "Case management (0-6) (DB17-20 methodology)": int,
    "Court automation (0-4) (DB17-20 methodology)": int,
    "Alternative dispute resolution (0-3) (DB17-20 methodology)": int,
    
    # Insolvency resolution
    "Rank-Resolving insolvency": int,
    "Score-Resolving insolvency": float,
    "Outcome (0 as piecemeal sale and 1 as going concern)": int,
    "Time (years)": float,
    "Cost (% of estate)": float,
    "Recovery rate (cents on the dollar)": float,
    "Score-Recovery rate (cents on the dollar)": float,
    "Strength of insolvency framework index (0-16)": int,
    "Score-Strength of insolvency framework index (0-16)": float,
    "Commencement of proceedings index (0-3) (DB15-20 methodology)": int,
    "Management of debtor's assets index (0-6) (DB15-20 methodology)": int,
    "Reorganization proceedings index (0-3) (DB15-20 methodology)": int,
    "Creditor participation index (0-4) (DB15-20 methodology)": int
}